#!/usr/bin/env sh

# YAMLLint Wrapper
# https://github.com/adrienverge/yamllint

if ! command -v yamllint >/dev/null 2>&1; then
  echo "YAMLLint is not installed (try \`brew install yamllint\`). Skipping YAML lint."
  exit 0
fi

if [ $# -eq 0 ]; then
  yamllint
else
  yamllint "$@"
fi

exit $?
